/* Automatically generated by 'build-entry.js' */

import Vue from 'vue';

// import ElementUI from 'element-ui';
// import 'element-ui/lib/theme-chalk/index.css';

import DatePicker from '../packages/date-picker/index';
import MultiSelect from '../packages/multi-select/index';
import PopDialog from '../packages/pop-dialog/index';
import CascaderSelect from '../packages/cascader-select/index';

interface componentsData {
  [name: string]: object;
}

const components: componentsData = {
  DatePicker,
  MultiSelect,
  PopDialog,
  CascaderSelect,
};

const install = (vue: typeof Vue) => {
  // vue.use(ElementUI);

  Object.keys(components).forEach(key => {
    vue.component(key, components[key]);
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.0.0',
  install,
};

export {
  DatePicker,
  MultiSelect,
  PopDialog,
  CascaderSelect
};
